"""Generate workflow YAML files with parameter grid combinations for synthetic editing."""

import itertools
import sys
from pathlib import Path


def _parse_comma_list(value, cast=str):
    """Parse a comma-separated string into a list of values."""
    if value is None:
        return []
    return [cast(v.strip()) for v in value.split(",") if v.strip()]


def _make_output_dirname(combo):
    """Create a descriptive directory name from a parameter combination.

    Example: {"steps": 4, "cfg-scale": 2.5} -> "steps4_cfg2.5"
    """
    parts = []
    short_names = {
        "steps": "steps",
        "cfg-scale": "cfg",
        "true-cfg-scale": "truecfg",
        "strength": "str",
        "lora": "lora",
        "model": "model",
    }
    for key, value in combo.items():
        short = short_names.get(key, key)
        # Clean value for directory name
        val_str = str(value).replace("/", "_").replace(":", "_")
        parts.append(f"{short}{val_str}")
    return "_".join(parts)


def _generate_sweep_steps(args):
    """Generate workflow steps from the Cartesian product of sweep parameters.

    Returns:
        (steps, sweep_params) where steps is a list of workflow step dicts
        and sweep_params is a dict of parameter names to their sweep values.
    """
    sweep_params = {}

    steps_vals = _parse_comma_list(args.steps, int)
    if steps_vals:
        sweep_params["steps"] = steps_vals

    cfg_vals = _parse_comma_list(args.cfg_scale, float)
    if cfg_vals:
        sweep_params["cfg-scale"] = cfg_vals

    true_cfg_vals = _parse_comma_list(args.true_cfg_scale, float)
    if true_cfg_vals:
        sweep_params["true-cfg-scale"] = true_cfg_vals

    strength_vals = _parse_comma_list(args.strength, float)
    if strength_vals:
        sweep_params["strength"] = strength_vals

    lora_vals = _parse_comma_list(args.lora, str)
    if lora_vals:
        sweep_params["lora"] = lora_vals

    model_vals = _parse_comma_list(args.model, str)
    if model_vals:
        sweep_params["model"] = model_vals

    if not sweep_params:
        print(
            "Error: At least one sweep parameter is required "
            "(--steps, --cfg-scale, --true-cfg-scale, --strength, --lora, --model)."
        )
        sys.exit(1)

    # Build Cartesian product
    param_names = list(sweep_params.keys())
    param_values = [sweep_params[k] for k in param_names]
    combinations = list(itertools.product(*param_values))

    base_output = args.output.rstrip("/")

    steps = []
    for combo_vals in combinations:
        combo = dict(zip(param_names, combo_vals))
        dirname = _make_output_dirname(combo)

        step_args = {
            "input": args.input,
            "output": f"{base_output}/{dirname}",
            "prompt": args.prompt,
        }

        # Add swept parameters
        for key, value in combo.items():
            if key == "lora":
                step_args["lora"] = [value]
            else:
                step_args[key] = value

        # Add pass-through parameters
        if args.seed is not None:
            step_args["seed"] = args.seed
        if args.output_format:
            step_args["output-format"] = args.output_format
        if getattr(args, "image_api", False):
            step_args["image-api"] = True
        if getattr(args, "base_model", None):
            step_args["model"] = args.base_model

        steps.append(
            {
                "command": "synthetic",
                "args": step_args,
            }
        )

    return steps, sweep_params


def cmd_sweep(args):
    """Execute the sweep command: generate workflow YAML from parameter grid."""
    try:
        import yaml
    except ImportError:
        print("Error: pyyaml is required for the sweep command.")
        print("Run: pip install pyyaml")
        sys.exit(1)

    steps, sweep_params = _generate_sweep_steps(args)

    workflow = {"steps": steps}

    # Build header comment
    total = len(steps)
    param_summary = ", ".join(
        f"{k}=[{', '.join(str(v) for v in vs)}]" for k, vs in sweep_params.items()
    )
    header = (
        f"# Generated by: datasety sweep\n"
        f"# Total combinations: {total}\n"
        f"# Parameters: {param_summary}\n"
    )

    yaml_content = header + yaml.dump(workflow, default_flow_style=False, sort_keys=False)

    output_file = Path(args.output_file)
    output_file.parent.mkdir(parents=True, exist_ok=True)
    output_file.write_text(yaml_content, encoding="utf-8")
    print(f"Generated {total} sweep combinations -> {output_file}")

    if args.run:
        print("-" * 50)
        print("Executing workflow...")
        import argparse

        from datasety.workflow import cmd_workflow

        # Create a fake args namespace for workflow execution
        wf_args = argparse.Namespace(file=str(output_file), dry_run=False)
        cmd_workflow(wf_args)
    else:
        print(f"Run the sweep with: datasety workflow -f {output_file}")


def register_parser(subparsers):
    """Register the sweep subcommand."""
    sweep_parser = subparsers.add_parser(
        "sweep",
        help="Generate workflow YAML with parameter grid combinations for synthetic editing",
    )
    sweep_parser.add_argument("--input", "-i", required=True, help="Input images directory")
    sweep_parser.add_argument(
        "--output",
        "-o",
        required=True,
        help="Base output directory (subdirectories created per combination)",
    )
    sweep_parser.add_argument(
        "--prompt", "-p", required=True, help="Edit prompt for synthetic command"
    )
    sweep_parser.add_argument(
        "--steps", default=None, help="Comma-separated step values to sweep (e.g., 4,8,16)"
    )
    sweep_parser.add_argument(
        "--cfg-scale",
        default=None,
        help="Comma-separated CFG scale values to sweep (e.g., 1.0,2.5,5.0)",
    )
    sweep_parser.add_argument(
        "--true-cfg-scale", default=None, help="Comma-separated true CFG values to sweep"
    )
    sweep_parser.add_argument(
        "--strength",
        default=None,
        help="Comma-separated strength values to sweep (e.g., 0.5,0.7,0.9)",
    )
    sweep_parser.add_argument("--lora", default=None, help="Comma-separated LoRA specs to sweep")
    sweep_parser.add_argument("--model", default=None, help="Comma-separated model names to sweep")
    sweep_parser.add_argument(
        "--seed", type=int, default=None, help="Random seed (passed through to each step)"
    )
    sweep_parser.add_argument(
        "--output-format",
        choices=["png", "jpg", "webp"],
        default=None,
        help="Output image format (passed through)",
    )
    sweep_parser.add_argument(
        "--output-file", default="sweep.yaml", help="Output YAML file path (default: sweep.yaml)"
    )
    sweep_parser.add_argument(
        "--image-api",
        action="store_true",
        help=(
            "Use OpenAI-compatible image API instead of local model"
            " (passed to each synthetic step)"
        ),
    )
    sweep_parser.add_argument(
        "--base-model",
        default=None,
        help="Base model to use for all synthetic steps (e.g., black-forest-labs/flux.2-klein-4b). "
        "Takes precedence over --model sweep when used with --image-api.",
    )
    sweep_parser.add_argument(
        "--run", action="store_true", help="Generate YAML and immediately execute the workflow"
    )
    sweep_parser.set_defaults(func=cmd_sweep)
